server:
  port: 8081 
  servlet:
    context-path: /api/v1  

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_user_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

# JWT configuration (will be used later in security)
jwt:
  secret: f3b939026f6b8c5ef2c6727b41d3409d9bc977d5f58070e64a88dd3bcdda6a6d  # Use env var in prod
  expiration: 86400000          # 1 day in ms
  refresh-expiration: 604800000 # 7 days in milliseconds

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true

# Logging
logging:
  level:
    com.ecommerce.user_service: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Swagger/OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html               

